import{i as l,a as y,S as B}from"./assets/vendor-C1DvvBV_.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();function d(e,s="success"){const r={message:e,position:"topRight",timeout:5e3};switch(s){case"success":l.success(r);break;case"error":l.error(r);break;case"warning":l.warning(r);break;case"info":l.info(r);break;default:l.error({message:"Invalid type of toast",timeout:5e3,position:"topRight"})}}function S(e){return e===""}y.defaults.baseURL="https://pixabay.com/";const q=15;async function m(e,s){const{data:r}=await y("api/",{params:{key:"57748887-33fc44c7a6eadcbc503de0d7e",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:q,page:s}});return r}const i={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more-btn")},g=new B(".gallery a",{captionsData:"alt",captionDelay:250});function h(e){const s=e.map(({largeImageURL:r,webformatURL:n,tags:t,likes:o,views:c,comments:v,downloads:M})=>`<li class="gallery-item">
  <a class="gallery-item" href="${r}">
  <img src="${n}" alt="${t}" />
</a>
  <div class="gallery-text-wrapper">
    <p class="likes"><span>Likes</span> ${o}</p>
    <p class="likes"><span>Views</span> ${c}</p>
    <p class="likes"><span>Comments</span> ${v}</p>
    <p class="likes"><span>Downloads</span> ${M}</p>
  </div>
</li>`).join("");i.gallery.insertAdjacentHTML("beforeend",s),g.refresh()}function k(){i.gallery.innerHTML=""}function b(){i.loader.classList.add("visible")}function L(){i.loader.classList.remove("visible")}function w(){i.loadMoreBtn.classList.add("visible")}function p(){i.loadMoreBtn.classList.remove("visible")}function P(){return document.querySelector(".gallery-item").getBoundingClientRect().height*2+24*2}function $(e){g.refresh(),window.scrollBy({top:e,behavior:"smooth"})}let a=1,u="",f=1;i.form.addEventListener("submit",H);i.loadMoreBtn.addEventListener("click",O);async function H(e){e.preventDefault();const s=e.currentTarget.elements["search-text"].value.trim().toLowerCase();if(s!==u?(u=s,a=1):a+=1,S(u)){e.target.reset();return}if(a>f)return d("We're sorry, but you've reached the end of search results","info");k(),p(),b();try{const{hits:r,totalHits:n}=await m(u,a);if(f=Math.ceil(n/15),r.length===0){d("Sorry, there are no images matching your search query. Please try again!","info");return}a<f&&w(),h(r)}catch(r){d(r.message,"error")}finally{L(),e.target.reset()}}async function O(){p(),b(),a+=1;try{const{hits:e}=await m(u,a);if(a<f)w();else{d("We're sorry, but you've reached the end of search results","info"),p();return}h(e),$(P())}catch(e){d(e.message,"error")}finally{L()}}
//# sourceMappingURL=index.js.map
