import{S as B,i as c,a as p}from"./assets/vendor-CWo9T4oQ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const a={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more-btn")},m=new B(".gallery a",{captionsData:"alt",captionDelay:250});function y(e){const r=e.map(({largeImageURL:s,webformatURL:l,tags:t,likes:o,views:n,comments:v,downloads:M})=>`<li class="gallery-item">
  <a class="gallery-item" href="${s}">
  <img src="${l}" alt="${t}" />
</a>
  <div class="gallery-text-wrapper">
    <p class="likes"><span>Likes</span> ${o}</p>
    <p class="likes"><span>Views</span> ${n}</p>
    <p class="likes"><span>Comments</span> ${v}</p>
    <p class="likes"><span>Downloads</span> ${M}</p>
  </div>
</li>`).join("");a.gallery.insertAdjacentHTML("beforeend",r),m.refresh()}function S(){a.gallery.innerHTML=""}function g(){a.loader.classList.add("visible")}function h(){a.loader.classList.remove("visible")}function k(){a.loadMoreBtn.classList.add("visible")}function b(){a.loadMoreBtn.classList.remove("visible")}function d(e,r="success"){const s={message:e,position:"topRight",timeout:5e3};switch(r){case"success":c.success(s);break;case"error":c.error(s);break;case"warning":c.warning(s);break;case"info":c.info(s);break;default:c.error({message:"Invalid type of toast",timeout:5e3,position:"topRight"})}}function q(e){return e===""}function L(e,r){e<r?k():d("We're sorry, but you've reached the end of search results","info")}p.defaults.baseURL="https://pixabay.com/";const P=15;async function w(e,r){const{data:s}=await p("api/",{params:{key:"57748887-33fc44c7a6eadcbc503de0d7e",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:r}});return s}let i=1,u="",f=1;a.form.addEventListener("submit",$);a.loadMoreBtn.addEventListener("click",C);async function $(e){if(e.preventDefault(),i=1,u=e.currentTarget.elements["search-text"].value.trim().toLowerCase(),q(u)){e.target.reset();return}S(),b(),g();try{const{hits:r,totalHits:s}=await w(u,i);if(f=Math.ceil(s/15),r.length===0){d("Sorry, there are no images matching your search query. Please try again!","info");return}L(i,f),y(r)}catch(r){d(r.message,"error")}finally{h(),e.target.reset()}}async function C(){b(),g(),i+=1;try{const{hits:e}=await w(u,i);L(i,f),y(e),O(H())}catch(e){d(e.message,"error")}finally{h()}}function H(){return document.querySelector(".gallery-item").getBoundingClientRect().height*2+24*2}function O(e){m.refresh(),window.scrollBy({top:e,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
